/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.traderepublic.mrschyzo.portfoliovaluation.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))

    implementation("org.postgresql:postgresql:42.5.4")

    implementation("com.datastax.oss:java-driver-core:4.16.0")

    testImplementation("org.testcontainers:testcontainers:1.18.3")
    testImplementation("org.testcontainers:postgresql:1.18.3")
    testImplementation("org.testcontainers:cassandra:1.18.3")
    testImplementation("org.testcontainers:influxdb:1.18.3")

    testImplementation("org.junit.jupiter:junit-jupiter:5.9.2")
    testImplementation("org.testcontainers:junit-jupiter:1.18.3")

}
repositories {
    mavenCentral()
}

application {
    // Define the main class for the application.
    mainClass.set("com.traderepublic.mrschyzo.portfoliovaluation.app.AppKt")
}

tasks {
    test {
        minHeapSize="8g"
        maxHeapSize="8g"

        useJUnitPlatform()

        testLogging {
            events("passed", "skipped", "failed", "standardError")

            showExceptions=true
            exceptionFormat=org.gradle.api.tasks.testing.logging.TestExceptionFormat.FULL
            showCauses=true
            showStackTraces=true

            showStandardStreams = false
        }
    }
}
